server:
  port: 8081
spring:
  application:
    name: auth
  profiles:
    active: dev
  config:
    import: 'optional:configserver:http://localhost:8888'
#JPA Connection details
spring.datasource:
  url: jdbc:mysql://localhost:3306/cropdeal
  username: root
  password: root
